// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.media.autoplay.default", 1);
user_pref("app.normandy.user_id", "c50de37d-77c8-4496-9d3b-70290d7eea1d");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1557914258);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1557914296);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1557914030);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{eb713fc4-70ce-44d6-901f-8cb80d666b88}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1557871200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.activity-stream.prerender", false);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1557914253841");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1557916052841");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1557914039744");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1557917639744");
user_pref("browser.search.region", "IT");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190409155332");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 1244);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20190409155332");
user_pref("browser.startup.homepage_override.mstone", "66.0.3");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1557914040190");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.3");
user_pref("distribution.iniFile.exists.value", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190409155332");
user_pref("extensions.lastAppVersion", "66.0.3");
user_pref("extensions.lastPlatformVersion", "66.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.update.enabled", false);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"f147fd66-c6e9-4f1c-a247-b5fe04a7d8d7\",\"screenshots@mozilla.org\":\"dec0291c-da2a-4b1e-868b-3a75ab3367ff\",\"webcompat-reporter@mozilla.org\":\"bb1365e5-1c8d-4f02-8767-e8bf9d437942\",\"webcompat@mozilla.org\":\"b1a11944-b2b2-4af8-a2ad-e146c3c7af67\",\"hotfix-update-xpi-intermediate@mozilla.com\":\"196006a6-ba22-4147-8075-6937d2114bed\"}");
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "66.0.3");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x5916");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "25.20.100.6576");
user_pref("layers.mlgpu.sanity-test-failed", false);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x5916");
user_pref("sanity-test.driver-version", "25.20.100.6576");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20190409155332");
user_pref("security.sandbox.content.tempDirSuffix", "{78485a48-8141-40ec-9d4f-e43dada11cd5}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{e0f12e7c-481f-456f-89a5-e6117ab04ef8}");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1557914265);
user_pref("toolkit.telemetry.cachedClientID", "e870ec9f-9b3f-4c74-8293-4f0a8c6becc1");
user_pref("toolkit.telemetry.previousBuildID", "20190409155332");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
